country_capitals_dict = {"Afghanistan":"Kābul","Albania":"Tiranë","Algeria":"Algiers","American Samoa":"Pago Pago",
"Andora":"Andorra La Vella","Angola":"Luanda","Antigua and Barbuda":"Saint John's","Armenia":"Yerevan",
"Argentina":"Buenos Aires","Australia":"Canberra","Austria":"Vienna","Azerbaijan":"Baku","Bahamas":"Nassau","Bahrain":"Manama",
"Bangladesh":"Dhaka","Barbados":"Bridgetown","Belarus":"Minsk","Belgium":"Brussels","Belize":"Belmopan","Benin":"Porto-Novo",
"Bhutan":"Thimphu","Bolivia":"Sucre La Paz","Bosnia and Herzegovina":"Sarajevo","Botswana":"Gaborone","Brazil":"Brasilia",
"Brunei":"Bandar Seri Begawan","Bulgaria":"Sofia","Burkina Faso":"Ouagadougou","Burundi":"Gitega","Cabo Verde":"Praia",
"Cambodia":"Phnom Penh","Cameroon":"Yaounde","Canada":"Ottawa","Central African Republic":"Bangui","Chad":"N'Djamena",
"Chile":"Santiago","China":"Beijing","Colombia":"Bogotá","Comoros":"Moroni","Democratic Republic of the Congo":"Kinshasa",
"Republic of the Congo":"Brazzaville","Costa Rica":"San Jose","Cote d'Ivoire":"Yamoussoukro","Croatia":"Zagreb","Cuba":"Havana",
"Cyprus":"Nicosia","Czechia":"Prague","Denmark":"Copenhagen","Djibouti":"Djibouti city","Dominica":"Roseau",
"Dominican Republic":"Santo Dominigo","Ecuador":"Quito","Egypt":"Cairo","El Salvador":"San Salvador",
"Equatorial Guinea":"Malabo, Oyala","Eritrea":"Asmara","Estonia":"Tallinn","Eswatini":"Mbabane Lobamba",
"Swaziland":"Mbabane Lobamba","Ethiopia":"Addis Ababa","Fiji":"Suva","Finland":"Helsinki","France":"Paris","Gabon":"Libreville",
"Gambia":"Banjul","Georgia":"Tbilisi","Germany":"Berlin","Ghana":"Accra","Greece":"Athens","Grenada":"Saint George's",
"Guatemala":"Guatemala City","Guinea":"Conakry","Guinea-Bissau":"Bissau","Guyana":"Georgetown","Haiti":"Port-au-Prince",
"Honduras":"Tegucigalpa","Hungary":"Budapest","Iceland":"Reykjavik","India":"New Delhi","Indonesia":"Jakarta","Iran":"Tehran",
"Iraq":"Bagdadh","Ireland":"Dublin","Israel":"Jerusalem","Italy":"Rome","Jamaica":"Kingston","Japan":"Tokyo","Jordan":"Amman",
"Kazakhstan":"Nur-Sultan","Kenya":"Nairobi","Kiribati":"Tarawa","Kosovo":"Pristina","Kuwait":"Kuwait City","Kyrgystan":"Bishkek",
"Laos":"Vientiane","Latvia":"Riga","Lebanon":"Beirut","Lesotho":"Maseru","Liberia":"Monrovia","Libya":"Tripoli",
"Liechtenstein":"Vaduz","Lithuania":"Vilnius","Luxembourg":"Luxembourg city","Madagascar":"Antananarivo","Malawi":"Lilongwe",
"Malayasia":"Kuala Lampur","Maldives":"Male","Mali":"Bamako","Malta":"Valetta","Marshall Islands":"Majuro",
"Mauritania":"Nouakchott","Mauritius":"Port Louis","Mexico":"Mexico City","Micronesia":"Palikir","Moldova":"Chisinau",
"Monaco":"Monaco","Mongolia":"Ulaanbataar","Montenegro":"Podgorica","Morocco":"Rabat","Mozambique":"Maputo",
"Myanmar":"Naypyidaw","Burma":"Naypidaw (This is the old name for Myanmar)","Namibia":"Windhoek","Nauru":"Yaren District",
"Nepal":"Kathmandu","Netherlands":"Amsterdam","New Zealand":"Wellington","Nicaragua":"Managua","Niger":"Niamey",
"Nigeria":"Abuja","North Korea":"Pyongyang","North Macedonia":"Skopje","Norway":"oslo","Oman":"Muscat","Pakistan":"Islamabad",
"Palau":"Ngerulmud","Palestine":"Jerusalem","Panama":"Panama City","Papua New Guinea":"Port Moresby","Paraguay":"Asunción",
"Peru":"Lima","Philippines":"Manila","Poland":"Warsaw","Portugal":"Lisbon","Qatar":"Doha","Romania":"Bucharest",
"Russia":"Moscow","Rwanda":"Kigali","Saint Kitts and Nevis":"Basseterre","Saint Lucia":"Castries",
"Saint Vincent and the Grenadines":"Kingstown","Samoa":"Apia","San Marino":"San Marino","Sao Tome and Principe":"São Tomé",
"Saudi Arabia":"Riyadh","Senegal":"Dakar","Serbia":"Belgrade","Seychelles":"Victoria","Sierra Leone":"Freetown",
"Singapore":"Singapore","Slovakia":"Bratislava","Slovenia":"Ljubljana","Solomon Islands":"Honiara","Somalia":"Mogadishu",
"South Africa":"Pretoria","South Korea":"Seoul","South Sudan":"Khartoum","Suriname":"Paramaribo","Sweden":"Stockholm",
"Switzerland":"Bern","Syria":"Damascus","Taiwan":"Taipei","Tajikistan":"Dushanbe","Tanzania":"Dodoma","Thailand":"Bangkok",
"Timor-Leste":"Dili","Togo":"Lome","Tonga":"Nukuʻalofa","Trinidad and Tobago":"Port of Spain","Tunisia":"Tunis",
"Turkey":"Ankara","Turkhmenistan":"Ashgabat","Tuvalu":"Funafuti","Uganda":"Kampala","Ukraine":"Kyiv",
"United Arab Emirates":"Abu Dhabi","United Kingdom":"London","United States of America":"Washington, D.C","Uruguay":"Montevideo",
"Uzbekistan":"Tashkent","Vanuatu":"Port Vila","Vatican City":"Vatican City","Venezuela":"Caracas","Vietnam":"Hanoi",
"Yemen":"Sana'a","Zambia":"Lusaka","Zimbabwe":"Harare","England":"London","Ireland":"Dublin","Scotland":"Edinburgh",
"Spain":"Madrid"}

def find(country):
	result = country_capitals_dict.get(country)
	return result